# Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [3]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [4]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.70876975,  1.67078373,  1.30664988],
       [-0.49915786,  1.94020584, -1.13725615, -1.02781144],
       [-0.96620614,  1.0144615 , -1.36189934, -1.15750374],
       [ 1.60255943,  0.32015325,  1.27765815,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.02493456, -1.02781144],
       [ 0.901987  , -0.14271892,  0.37908538,  0.26911151],
       [-1.19973028,  0.78302542, -1.02493456, -1.28719604],
       [-0.61591993,  1.47733367, -1.24957775, -1.28719604],
       [-0.49915786,  1.47733367, -1.24957775, -1.28719604],
       [-0.03210957, -0.83702717,  0.77221097,  0.91757299],
       [-1.31649236,  0.32015325, -1.19341695, -1.28719604],
       [ 1.25227322,  0.08871717,  0.94069336,  1.17695758],
       [-1.08296821,  0.08871717, -1.24957775, -1.41688833],
       [-1.08296821, -1.29989934,  0.43524618,  0.6581884 ],
       [ 0.43493872, -0.374155  ,  0.32292459,  0.13941922],
       [ 1.60255943,  1.24589758,  1.33381894,  1.69572677],
       [ 0.31817664, -0.374155  ,  0.54756778,  0.26911151],
       [ 1.83608357, -0.60559109,  1.33381894,  0.91757299],
       [-0.03210957, -0.83702717,  0.0982814 ,  0.00972692],
       [ 0.20141457, -1.99420759,  0.71605017,  0.39880381],
       [ 1.01874907,  0.08871717,  1.05301496,  1.56603447],
       [-0.84944407,  1.0144615 , -1.30573855, -1.15750374],
       [-0.14887164, -0.14271892,  0.26676379,  0.00972692],
       [-0.38239578, -1.53133542,  0.0421206 , -0.11996537],
       [ 0.55170079, -1.29989934,  0.71605017,  0.91757299],
       [ 1.48579736, -0.14271892,  1.22149735,  1.17695758],
       [-0.38239578, -1.06846325,  0.37908538,  0.00972692],
       [-0.96620614, -1.7627715 , -0.23868339, -0.24965767],
       [ 1.25227322,  0.08871717,  0.77221097,  1.43634218],
       [ 0.66846286, -0.60559109,  1.05301496,  1.17695758],
       [ 0.43493872, -1.99420759,  0.43524618,  0.39880381],
       [-0.14887164, -0.60559109,  0.43524618,  0.13941922],
       [-0.732682  , -0.83702717,  0.0982814 ,  0.26911151],
       [ 2.06960772, -0.14271892,  1.61462293,  1.17695758],
       [ 1.13551115, -0.60559109,  0.60372857,  0.26911151],
       [-0.84944407, -1.29989934, -0.40716578, -0.11996537],
       [-0.14887164, -1.29989934,  0.71605017,  1.04726529],
       [ 0.66846286, -0.374155  ,  0.32292459,  0.13941922],
       [ 1.01874907,  0.08871717,  0.37908538,  0.26911151],
       [-0.26563371, -0.83702717,  0.26676379,  0.13941922],
       [ 1.25227322,  0.08871717,  0.65988937,  0.39880381],
       [-0.84944407,  0.55158933, -1.13725615, -0.89811915],
       [-1.08296821, -0.14271892, -1.30573855, -1.28719604],
       [ 0.20141457, -0.83702717,  0.77221097,  0.52849611],
       [-1.08296821, -1.53133542, -0.23868339, -0.24965767],
       [-0.03210957,  2.17164192, -1.41806014, -1.28719604],
       [-0.96620614,  1.0144615 , -1.19341695, -0.76842685],
       [ 0.55170079, -0.83702717,  0.65988937,  0.7878807 ],
       [ 1.7193215 , -0.374155  ,  1.44614054,  0.7878807 ],
       [-0.732682  ,  2.403078  , -1.24957775, -1.41688833],
       [-0.14887164,  3.09738625, -1.24957775, -1.02781144],
       [ 1.13551115, -0.14271892,  0.99685416,  1.17695758],
       [-1.43325443,  0.08871717, -1.24957775, -1.28719604],
       [-0.03210957, -0.83702717,  0.21060299, -0.24965767],
       [ 1.01874907, -0.14271892,  0.82837177,  1.43634218],
       [ 1.36903529,  0.32015325,  0.54756778,  0.26911151],
       [-0.96620614,  0.32015325, -1.41806014, -1.28719604],
       [-0.96620614,  0.78302542, -1.24957775, -1.28719604],
       [ 0.55170079,  0.55158933,  1.27765815,  1.69572677],
       [ 2.18636979, -0.60559109,  1.67078373,  1.04726529],
       [ 0.0846525 , -0.14271892,  0.26676379,  0.39880381],
       [-1.31649236,  0.32015325, -1.36189934, -1.28719604],
       [ 0.66846286,  0.32015325,  0.88453256,  1.43634218],
       [-0.96620614,  0.78302542, -1.19341695, -1.02781144],
       [ 0.20141457,  0.78302542,  0.43524618,  0.52849611],
       [-1.19973028, -0.14271892, -1.30573855, -1.41688833],
       [ 1.01874907,  0.55158933,  1.10917575,  1.17695758],
       [ 0.78522493, -0.60559109,  0.49140698,  0.39880381],
       [-1.43325443,  1.24589758, -1.53038174, -1.28719604],
       [-0.03210957, -0.60559109,  0.77221097,  1.56603447],
       [-1.78354064, -0.14271892, -1.47422094, -1.41688833],
       [ 1.01874907, -1.29989934,  1.16533655,  0.7878807 ],
       [-1.08296821,  1.24589758, -1.30573855, -1.41688833],
       [-0.49915786,  1.94020584, -1.36189934, -1.02781144],
       [-1.43325443,  0.32015325, -1.30573855, -1.28719604],
       [-0.03210957, -0.83702717,  0.77221097,  0.91757299],
       [ 0.55170079, -0.60559109,  0.77221097,  0.39880381],
       [-0.96620614,  0.55158933, -1.30573855, -1.28719604],
       [ 2.41989393,  1.70876975,  1.50230134,  1.04726529],
       [-1.66677857,  0.32015325, -1.36189934, -1.28719604],
       [-1.19973028, -0.14271892, -1.30573855, -1.15750374],
       [ 1.01874907,  0.55158933,  1.10917575,  1.69572677],
       [-0.96620614, -2.45707976, -0.12636179, -0.24965767],
       [-0.732682  ,  1.0144615 , -1.24957775, -1.28719604],
       [ 2.18636979, -1.06846325,  1.78310533,  1.43634218],
       [ 1.13551115,  0.32015325,  1.22149735,  1.43634218],
       [-0.96620614, -0.14271892, -1.19341695, -1.28719604],
       [-0.84944407,  1.47733367, -1.24957775, -1.02781144],
       [ 2.18636979, -0.14271892,  1.33381894,  1.43634218],
       [-0.14887164,  1.70876975, -1.13725615, -1.15750374],
       [-0.26563371, -0.14271892,  0.43524618,  0.39880381],
       [-1.19973028,  0.08871717, -1.19341695, -1.28719604],
       [ 0.78522493, -0.14271892,  1.16533655,  1.30664988],
       [ 0.901987  , -0.374155  ,  0.49140698,  0.13941922],
       [-0.732682  ,  0.78302542, -1.30573855, -1.28719604],
       [-0.84944407,  1.70876975, -1.19341695, -1.28719604],
       [-1.43325443,  0.78302542, -1.30573855, -1.15750374],
       [-0.03210957, -1.06846325,  0.15444219,  0.00972692],
       [-1.08296821,  0.08871717, -1.24957775, -1.28719604],
       [-0.26563371, -0.374155  , -0.070201  ,  0.13941922],
       [ 0.31817664, -0.14271892,  0.49140698,  0.26911151],
       [-0.38239578, -1.53133542, -0.0140402 , -0.24965767],
       [ 0.66846286,  0.32015325,  0.43524618,  0.39880381],
       [-0.84944407,  1.0144615 , -1.30573855, -1.28719604]])

In [5]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.78302542, -1.19341695, -1.28719604],
       [ 0.20141457, -1.99420759,  0.15444219, -0.24965767],
       [ 0.55170079, -1.29989934,  0.65988937,  0.39880381],
       [ 1.25227322,  0.32015325,  1.10917575,  1.43634218],
       [-1.66677857, -0.374155  , -1.30573855, -1.28719604],
       [ 0.78522493, -0.14271892,  0.82837177,  1.04726529],
       [ 1.01874907, -0.14271892,  0.71605017,  0.6581884 ],
       [ 1.01874907,  0.08871717,  0.54756778,  0.39880381],
       [ 1.60255943, -0.14271892,  1.16533655,  0.52849611],
       [-0.96620614,  1.24589758, -1.30573855, -1.28719604],
       [-0.49915786,  0.78302542, -1.24957775, -1.02781144],
       [ 0.55170079,  0.78302542,  1.05301496,  1.56603447],
       [ 0.66846286, -0.60559109,  1.05301496,  1.30664988],
       [-0.26563371, -0.14271892,  0.21060299,  0.13941922]])

## One VS Rest 구현

In [6]:
svm_1 = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)
svm_2 = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)
svm_3 = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)

In [7]:
y_train = pd.get_dummies(y_train)
y_train

     setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [8]:
svm_1.fit(X_train,y_train.iloc[:,0]) # setosa 인지 아닌지 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # versicolor 인지 아닌지 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # virginica 인지 아닌지 구분해주는 머신
y_pred_1=svm_1.predict(X_test)
y_pred_2=svm_2.predict(X_test)
y_pred_3=svm_3.predict(X_test)
print(y_pred_1)
print(y_pred_2)
print(y_pred_3)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 1]
[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]

### decision_function 활용

In [9]:
for i in range(len(X_test)):
  if svm_1.predict(X_test)[i] == svm_2.predict(X_test)[i] == svm_3.predict(X_test)[i]:
    print(f"Index [{i}]에서 동점.")

Index [2]에서 동점.
Index [3]에서 동점.
Index [18]에서 동점.

Index 2, 3, 18에서 동점 데이터를 가짐\
이를 해결하기 위해 decision_function을 이용\
decision_function : 표본 데이터에 대해 판별함수값을 계산 / 수치가 크면 그 클래스일 가능성이 크고 수치가 작으면 그 클래스일 가능성이 낮기 때문에 세 개의 모델 중 decision_function 값이 가장 큰 것으로 예측 결과 내보내기로 한다.

In [10]:
def svm_ovr(models_ovr, data):
  d=[]
  result=[]
  for m in models_ovr:
    d.append(m.decision_function(data))
  
  for p in d:
    winner = np.argmax(d, axis=0)

  return pd.DataFrame(winner, columns=['ovr_pred']).replace({0:'setosa', 1:'versicolor', 2:'virginica'})

models_ovr = [svm_1, svm_2, svm_3]

svm_ovr(models_ovr, X_test)

      ovr_pred
0   versicolor
1   versicolor
2    virginica
3    virginica
4    virginica
5    virginica
6       setosa
7    virginica
8       setosa
9   versicolor
10   virginica
11      setosa
12      setosa
13   virginica
14  versicolor
15  versicolor
16      setosa
17  versicolor
18   virginica
19   virginica
20      setosa
21   virginica
22  versicolor
23  versicolor
24   virginica
25      setosa
26      setosa
27   virginica
28   virginica
29  versicolor

In [11]:
accuracy_score(y_test,svm_ovr(models_ovr, X_test))

0.9

## One Vs One 구현

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)
X_train, X_test = standardization(X_train, X_test)

In [13]:
n_se=pd.get_dummies(y_train[y_train != "setosa"], drop_first=True) # versicolor인지 virginica 인지를 구분
n_ve=pd.get_dummies(y_train[y_train != "versicolor"], drop_first=True) # setosa인지 virginica 인지를 구분
n_vi=pd.get_dummies(y_train[y_train != "virginica"], drop_first=True) # setosa인지 versicolor인지를 구분

In [14]:
# 어떤게 1인지 확인하기 위함
print(n_se.head(1))
print(n_ve.head(1))
print(n_vi.head(1))

     virginica
110          1
     virginica
110          1
    versicolor
69           1

In [15]:
# 학습을 위한 각각의 X 데이터 생성
x_n_se = X_train[y_train != "setosa"]
x_n_ve = X_train[y_train != "versicolor"]
x_n_vi = X_train[y_train != "virginica"]

In [16]:
svm_1_ovo = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)
svm_2_ovo = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)
svm_3_ovo = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)

In [17]:
svm_1_ovo.fit(x_n_se, n_se) # versicolor인지 virginica 인지를 구분해주는 머신
svm_2_ovo.fit(x_n_ve, n_ve) # setosa인지 virginica 인지를 구분해주는 머신
svm_3_ovo.fit(x_n_vi, n_vi) # setosa인지 versicolor인지를 구분해주는 머신
y_pred_1_ovo=svm_1_ovo.predict(X_test) # 1: virginica, 0: versicolor
y_pred_2_ovo=svm_2_ovo.predict(X_test) # 1: virginica, 0: setosa
y_pred_3_ovo=svm_3_ovo.predict(X_test) # 1: versicolor, 0: setosa
print(y_pred_1_ovo)
print(y_pred_2_ovo)
print(y_pred_3_ovo)

[0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0]
[1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1]
[1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [18]:
def svm_ovo(models_ovo, data):
  pred=[]
  result=[]

  for m in models_ovo:
    pred.append(m.predict(data))
 
  for i in range(np.shape(pred)[1]):
    score=np.array([0, 0, 0]) # setosa, versicolor, virginica 순서로의 score 세팅
    if pred[0][i] == 1: # virginica라면
      score[2]+=1
    elif pred[0][i] == 0: # versicolor라면
      score[1]+=1

    if pred[1][i] == 1: # virginica라면
      score[2]+=1
    elif pred[1][i] == 0: # setosa라면
      score[0]+=1

    if pred[2][i] == 1: # versicolor라면
      score[1]+=1
    elif pred[2][i] == 0: # setosa라면
      score[0]+=1
    
    result.append(score.argmax())
  
  return pd.DataFrame(result, columns=['ovo_pred']).replace({0:'setosa', 1:'versicolor', 2:'virginica'})

In [19]:
models_ovo = [svm_1_ovo, svm_2_ovo, svm_3_ovo]
svm_ovo(models_ovo, X_test)

      ovo_pred
0   versicolor
1   versicolor
2    virginica
3    virginica
4    virginica
5    virginica
6       setosa
7    virginica
8       setosa
9   versicolor
10   virginica
11      setosa
12      setosa
13   virginica
14  versicolor
15  versicolor
16      setosa
17  versicolor
18   virginica
19   virginica
20      setosa
21   virginica
22  versicolor
23  versicolor
24   virginica
25      setosa
26      setosa
27   virginica
28   virginica
29  versicolor

In [20]:
accuracy_score(y_test,svm_ovo(models_ovo, X_test))

0.9

## Compare Result

sklearn에서 제공하는 라이브러리로 비교

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)
X_train, X_test = standardization(X_train, X_test)

svm = SVC(kernel ='rbf', C = 2, gamma = 2, random_state=48)
svm.fit(X_train, y_train)
y_pred = pd.DataFrame({'sklearn_pred':svm.predict(X_test).tolist()})
y_pred

   sklearn_pred
0    versicolor
1    versicolor
2     virginica
3     virginica
4     virginica
5     virginica
6        setosa
7     virginica
8        setosa
9    versicolor
10    virginica
11       setosa
12       setosa
13    virginica
14   versicolor
15   versicolor
16       setosa
17   versicolor
18    virginica
19    virginica
20       setosa
21    virginica
22   versicolor
23   versicolor
24    virginica
25       setosa
26       setosa
27    virginica
28    virginica
29   versicolor

In [22]:
accuracy_score(y_test,y_pred)

0.9

In [23]:
all_result=pd.concat([y_pred, svm_ovo(models_ovo, X_test), svm_ovr(models_ovr, X_test)],1)
all_result

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  """Entry point for launching an IPython kernel.

   sklearn_pred    ovo_pred    ovr_pred
0    versicolor  versicolor  versicolor
1    versicolor  versicolor  versicolor
2     virginica   virginica   virginica
3     virginica   virginica   virginica
4     virginica   virginica   virginica
5     virginica   virginica   virginica
6        setosa      setosa      setosa
7     virginica   virginica   virginica
8        setosa      setosa      setosa
9    versicolor  versicolor  versicolor
10    virginica   virginica   virginica
11       setosa      setosa      setosa
12       setosa      setosa      setosa
13    virginica   virginica   virginica
14   versicolor  versicolor  versicolor
15   versicolor  versicolor  versicolor
16       setosa      setosa      setosa
17   versicolor  versicolor  versicolor
18    virginica   virginica   virginica
19    virginica   virginica   virginica
20       setosa      setosa      setosa
21    virginica   virginica   virginica
22   versicolor  versicolor  versicolor
23   versicolor  versicolor  versicolor
24    virginica   virginica   virginica
25       setosa      setosa      setosa
26       setosa      setosa      setosa
27    virginica   virginica   virginica
28    virginica   virginica   virginica
29   versicolor  versicolor  versicolor

In [24]:
print(f"sklearn_pred의 acc: {accuracy_score(y_test,y_pred)}")
print(f"ovo_pred의 acc: {accuracy_score(y_test,svm_ovo(models_ovo, X_test))}")
print(f"ovr_pred의 acc: {accuracy_score(y_test,svm_ovr(models_ovr, X_test))}")

sklearn_pred의 acc: 0.9
ovo_pred의 acc: 0.9
ovr_pred의 acc: 0.9

세 개의 결과가 모두 동일하다